import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
      <link href="https://db.onlinewebfonts.com/c/2b3966678f6a1c8c8be202caeb49d95a?family=FOT-Yuruka+Std" rel="stylesheet" type="text/css"/>			</head>
			<body className={`bg-dark-invert ${inter.className}`} style={{ fontFamily: "FOT-Yuruka Std" }}>
        <Navbar/>
				{children}
			</body>
		</html>
	);
}
